Custom training loop
FluxML/MLJFlux.jl pull request #95
Opened 2021-02-28 11:12 UTC by ayush-1506

Changes include:

- New custom training loop (`MLJFlux.train!`)
- Changes in `collate`
- Change `MLJFlux.fit!` signature everywhere.
- Adapting tests to these changes.

Fixes: #89

2021-02-28 11:14 UTC, ayush-1506 commented
@ablaom Should the head of this PR be `dev` or `master` branch?

2021-03-01 00:28 UTC, ablaom commented on src/core.jl
> -               lambda, alpha, verbosity, data, acceleration)
The doc string still has the old signature.

2021-03-01 00:28 UTC, ablaom commented on src/core.jl
> -               lambda, alpha, verbosity, data, acceleration)
And needs other fixes to reflect new behaviour.

2021-03-01 00:34 UTC, ablaom commented on test/core.jl
> +    @test  first.(data) == (Float32.(cat(Xmatrix[1], Xmatrix[2], dims=4)), [1 0;0 1])
We've reduced test coverage here. Could we just test the whole `data` array (sucking in the target test that follows)?

2021-03-01 00:35 UTC, ablaom requested changes
Fantastic work! Many thanks. 

Just those small items.

2021-03-02 21:21 UTC, ablaom approved these changes

2021-03-02 21:23 UTC, ablaom commented
@ayush-1506 Again many thanks

2021-03-02 21:23 UTC, merged